def _tagDefs():
	tags = { 'Every pulse':  [ 'dq',
							   'dt',
							   'ip',
							   'iq',
							   'mq',
							   'pa',
							   'pc',
							   'pd',
							   'pg',
							   'pm',
							   'pq',
							   'pt',
							   'pv',
							   'pw',
							   'px',
							   'sf',
							   'sq',
							   'st' ],
			 'Every subread':  [ '# not modified: cx',
			 					 '# not modified: np',
			 					 '# not modified: qe',
			 					 '# not modified: qs',
			 					 '# not modified: zm',
			 					 '# not modified: sn',
			 					 '# not modified: rq',
			 					 '# not modified: RG' ] }

	return tags